"""
utils.py — small helper functions used across the app.
"""

import requests
from bs4 import BeautifulSoup


def fetch_page_title(url: str) -> str | None:
    """
    Try to retrieve the HTML <title> tag from a URL.
    Returns the title string on success, or None if anything goes wrong
    (network error, timeout, paywall, malformed HTML, etc.).
    The caller decides how to handle None.
    """
    try:
        headers = {
            # Mimic a browser so sites don't block the request
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/122.0.0.0 Safari/537.36"
            )
        }
        response = requests.get(url, timeout=6, headers=headers)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        tag = soup.find("title")
        if tag and tag.string:
            return tag.string.strip()
    except Exception:
        pass
    return None


def parse_tags(raw: str) -> list:
    """
    Turn a comma-separated tag string into a clean list of lowercase strings.
    Example: " CBT,  Anxiety , " -> ["cbt", "anxiety"]
    """
    return [t.strip().lower() for t in raw.split(",") if t.strip()]


def format_date(dt_str: str) -> str:
    """
    Format a SQLite datetime string (e.g. '2024-03-15 09:42:00')
    into a readable short form like 'Mar 15, 2024'.
    Returns the original string if parsing fails.
    """
    if not dt_str:
        return ""
    try:
        from datetime import datetime
        dt = datetime.strptime(dt_str[:19], "%Y-%m-%d %H:%M:%S")
        return dt.strftime("%b %-d, %Y")
    except Exception:
        return dt_str[:10]


# ─── Markdown export ──────────────────────────────────────────────────────────

def item_to_markdown(item, tags: list, links: list = None) -> str:
    """
    Render a single library item as clean, readable markdown.
    `item` can be a sqlite3.Row or a dict — both support bracket access.
    `links` is the list of item_links rows for this item (from get_item_links).
    """
    lines = [f"# {item['title']}", ""]

    # Metadata block
    if item["content_type_name"]:
        lines.append(f"**Type:** {item['content_type_name']}")
    if item["created_at"]:
        lines.append(f"**Captured:** {format_date(item['created_at'])}")
    if item["url"]:
        lines.append(f"**Source:** [{item['url']}]({item['url']})")
    if tags:
        lines.append("**Tags:** " + " ".join(f"`{t}`" for t in tags))
    if item["impact_rating"]:
        stars = "★" * item["impact_rating"] + "☆" * (5 - item["impact_rating"])
        lines.append(f"**Impact:** {stars}")

    # Body / notes
    if item["body"]:
        lines += ["", "## Notes", item["body"]]

    # AI results
    if item["ai_summary"]:
        lines += ["", "## Summary", item["ai_summary"]]
    if item["ai_insight"]:
        lines += ["", "## Actionable Insight", item["ai_insight"]]

    # User synthesis
    if item["synthesis_note"]:
        lines += ["", "## My Synthesis", item["synthesis_note"]]

    # Manual links
    if links:
        lines += ["", "## Links"]
        for link in links:
            arrow = "→" if link["is_outgoing"] else "←"
            label = link["relationship_label"] or "linked"
            lines.append(f"- {arrow} **{link['other_title']}** _{label}_")

    lines += ["", "---", f"*Exported from PKM App · {format_date(item['created_at'])}*"]
    return "\n".join(lines)


def framework_to_markdown(framework: dict) -> str:
    """Render a generated framework dict as structured markdown."""
    from datetime import date as _date

    lines = [f"# {framework['name']}", ""]

    if framework.get("tagline"):
        lines += [f"> {framework['tagline']}", ""]

    if framework.get("description"):
        lines += ["## Overview", framework["description"], ""]

    components = framework.get("components", [])
    if components:
        lines += ["## Components", ""]
        for comp in components:
            lines.append(f"### {comp.get('name', 'Component')}")
            if comp.get("description"):
                lines.append(comp["description"])
            if comp.get("application"):
                lines += ["", f"**In practice:** {comp['application']}"]
            lines.append("")

    if framework.get("how_to_use"):
        lines += ["## How to Apply This Framework", framework["how_to_use"], ""]

    source_items = framework.get("source_items", [])
    if source_items:
        lines.append("## Built From")
        for title in source_items:
            lines.append(f"- {title}")
        lines.append("")

    lines += ["---", f"*Framework generated by PKM App · {_date.today().strftime('%B %-d, %Y')}*"]
    return "\n".join(lines)


def digest_to_markdown(digest_text: str, days: int = 7) -> str:
    """Wrap the AI digest text with a dated header for download."""
    from datetime import date as _date, timedelta

    today = _date.today()
    since = today - timedelta(days=days)
    header = (
        f"# Weekly Digest\n\n"
        f"*{since.strftime('%B %-d')} – {today.strftime('%B %-d, %Y')}*\n\n"
        "---\n\n"
    )
    footer = "\n\n---\n*Generated by PKM App*"
    return header + digest_text + footer


def safe_filename(text: str, max_len: int = 40) -> str:
    """Turn arbitrary text into a safe lowercase filename (no extension)."""
    return "".join(c if c.isalnum() else "_" for c in text[:max_len]).lower().strip("_")


def fetch_article_content(url: str) -> dict:
    """
    Fetch and extract the main readable text from an article URL.
    Returns {"title": str, "text": str, "error": str|None}.
    Uses BeautifulSoup heuristics to find the main body (article/main tag).
    """
    import re

    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/122.0.0.0 Safari/537.36"
        )
    }
    try:
        resp = requests.get(url, timeout=10, headers=headers)
        resp.raise_for_status()
        soup = BeautifulSoup(resp.text, "html.parser")

        # Remove noisy elements
        for tag in soup(["script", "style", "nav", "footer", "header", "aside",
                         "form", "noscript", "iframe", "svg"]):
            tag.decompose()

        title_tag = soup.find("title")
        title = title_tag.string.strip() if title_tag and title_tag.string else ""

        # Try to isolate the article body
        main = (
            soup.find("article")
            or soup.find("main")
            or soup.find(id=lambda x: x and any(k in x.lower() for k in ["article", "content", "post", "story"]))
            or soup.find(class_=lambda x: x and any(k in " ".join(x).lower() for k in ["article", "post-content", "entry-content", "story"]))
        )
        body = main or soup.find("body")
        text = body.get_text(separator="\n", strip=True) if body else ""

        # Collapse excessive blank lines
        text = re.sub(r"\n{3,}", "\n\n", text)
        text = text[:20000]  # cap to keep things fast

        return {"title": title, "text": text, "error": None}
    except Exception as exc:
        return {"title": "", "text": "", "error": str(exc)}


def parse_kindle_clippings(raw: str) -> list:
    """
    Parse a Kindle My Clippings.txt file into a list of highlight dicts.

    Each dict:
      {title, author, location, added_on, text}

    The file format separates entries with '==========' lines.
    Entry structure:
      Line 1: Book Title (Author Name)
      Line 2: - Your Highlight on Location 1234-1236 | Added on <date>
      Line 3: (blank)
      Line 4+: Highlight text
    """
    import re

    highlights = []
    entries = [e.strip() for e in raw.split("==========") if e.strip()]

    for entry in entries:
        lines = [l.strip() for l in entry.splitlines() if l.strip()]
        if len(lines) < 3:
            continue

        # Line 0: "Title (Author)" — author part is optional
        header = lines[0]
        author_match = re.search(r"\(([^)]+)\)\s*$", header)
        author = author_match.group(1) if author_match else ""
        title = header[: author_match.start()].strip() if author_match else header

        # Line 1: metadata (location / date)
        meta = lines[1]
        loc_match = re.search(r"[Ll]ocation (\S+)", meta)
        location = loc_match.group(1) if loc_match else ""
        date_match = re.search(r"Added on (.+)$", meta)
        added_on = date_match.group(1).strip() if date_match else ""

        # Skip non-highlight entries (bookmarks, notes without text)
        if "Bookmark" in meta or "Note" in meta:
            continue

        # Remaining lines are the highlight text
        text = " ".join(lines[2:]).strip()
        if not text:
            continue

        source = f"{title}" + (f", {author}" if author else "") + (f" — loc. {location}" if location else "")

        highlights.append({
            "title": title,
            "author": author,
            "location": location,
            "added_on": added_on,
            "text": text,
            "source_info": source,
        })

    return highlights
