"""
utils.py — small helper functions used across the app.
"""

import requests
from bs4 import BeautifulSoup


def fetch_page_title(url: str) -> str | None:
    """
    Try to retrieve the HTML <title> tag from a URL.
    Returns the title string on success, or None if anything goes wrong
    (network error, timeout, paywall, malformed HTML, etc.).
    The caller decides how to handle None.
    """
    try:
        headers = {
            # Mimic a browser so sites don't block the request
            "User-Agent": (
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/122.0.0.0 Safari/537.36"
            )
        }
        response = requests.get(url, timeout=6, headers=headers)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, "html.parser")
        tag = soup.find("title")
        if tag and tag.string:
            return tag.string.strip()
    except Exception:
        pass
    return None


def parse_tags(raw: str) -> list:
    """
    Turn a comma-separated tag string into a clean list of lowercase strings.
    Example: " CBT,  Anxiety , " -> ["cbt", "anxiety"]
    """
    return [t.strip().lower() for t in raw.split(",") if t.strip()]


def format_date(dt_str: str) -> str:
    """
    Format a SQLite datetime string (e.g. '2024-03-15 09:42:00')
    into a readable short form like 'Mar 15, 2024'.
    Returns the original string if parsing fails.
    """
    if not dt_str:
        return ""
    try:
        from datetime import datetime
        dt = datetime.strptime(dt_str[:19], "%Y-%m-%d %H:%M:%S")
        return dt.strftime("%b %-d, %Y")
    except Exception:
        return dt_str[:10]


# ─── Markdown export ──────────────────────────────────────────────────────────

def item_to_markdown(item, tags: list, links: list = None) -> str:
    """
    Render a single library item as clean, readable markdown.
    `item` can be a sqlite3.Row or a dict — both support bracket access.
    `links` is the list of item_links rows for this item (from get_item_links).
    """
    lines = [f"# {item['title']}", ""]

    # Metadata block
    if item["content_type_name"]:
        lines.append(f"**Type:** {item['content_type_name']}")
    if item["created_at"]:
        lines.append(f"**Captured:** {format_date(item['created_at'])}")
    if item["url"]:
        lines.append(f"**Source:** [{item['url']}]({item['url']})")
    if tags:
        lines.append("**Tags:** " + " ".join(f"`{t}`" for t in tags))
    if item["impact_rating"]:
        stars = "★" * item["impact_rating"] + "☆" * (5 - item["impact_rating"])
        lines.append(f"**Impact:** {stars}")

    # Body / notes
    if item["body"]:
        lines += ["", "## Notes", item["body"]]

    # AI results
    if item["ai_summary"]:
        lines += ["", "## Summary", item["ai_summary"]]
    if item["ai_insight"]:
        lines += ["", "## Actionable Insight", item["ai_insight"]]

    # User synthesis
    if item["synthesis_note"]:
        lines += ["", "## My Synthesis", item["synthesis_note"]]

    # Manual links
    if links:
        lines += ["", "## Links"]
        for link in links:
            arrow = "→" if link["is_outgoing"] else "←"
            label = link["relationship_label"] or "linked"
            lines.append(f"- {arrow} **{link['other_title']}** _{label}_")

    lines += ["", "---", f"*Exported from PKM App · {format_date(item['created_at'])}*"]
    return "\n".join(lines)


def framework_to_markdown(framework: dict) -> str:
    """Render a generated framework dict as structured markdown."""
    from datetime import date as _date

    lines = [f"# {framework['name']}", ""]

    if framework.get("tagline"):
        lines += [f"> {framework['tagline']}", ""]

    if framework.get("description"):
        lines += ["## Overview", framework["description"], ""]

    components = framework.get("components", [])
    if components:
        lines += ["## Components", ""]
        for comp in components:
            lines.append(f"### {comp.get('name', 'Component')}")
            if comp.get("description"):
                lines.append(comp["description"])
            if comp.get("application"):
                lines += ["", f"**In practice:** {comp['application']}"]
            lines.append("")

    if framework.get("how_to_use"):
        lines += ["## How to Apply This Framework", framework["how_to_use"], ""]

    source_items = framework.get("source_items", [])
    if source_items:
        lines.append("## Built From")
        for title in source_items:
            lines.append(f"- {title}")
        lines.append("")

    lines += ["---", f"*Framework generated by PKM App · {_date.today().strftime('%B %-d, %Y')}*"]
    return "\n".join(lines)


def digest_to_markdown(digest_text: str, days: int = 7) -> str:
    """Wrap the AI digest text with a dated header for download."""
    from datetime import date as _date, timedelta

    today = _date.today()
    since = today - timedelta(days=days)
    header = (
        f"# Weekly Digest\n\n"
        f"*{since.strftime('%B %-d')} – {today.strftime('%B %-d, %Y')}*\n\n"
        "---\n\n"
    )
    footer = "\n\n---\n*Generated by PKM App*"
    return header + digest_text + footer


def safe_filename(text: str, max_len: int = 40) -> str:
    """Turn arbitrary text into a safe lowercase filename (no extension)."""
    return "".join(c if c.isalnum() else "_" for c in text[:max_len]).lower().strip("_")
